name: Test
on: push

jobs:
  # Run the linter first for rapid feedback if some trivial stylistic issues
  # slipped through the cracks.
  lint:
    runs-on: ubuntu-latest
    env:
      # When running in CI the gemspec does NOT pull rubocop as a dependency
      # to avoid conflicting with various Ruby/Rails setups. We need to
      # set LINT to explicitly request rubocop as a dependency.
      LINT: true
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
      - run: bundle exec rake rubocop

  test:
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: active_record_doctor_test
          POSTGRES_USER: github
          POSTGRES_PASSWORD: github
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: github
          MYSQL_USER: github
          MYSQL_PASSWORD: github
          MYSQL_DATABASE: active_record_doctor_test
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    strategy:
      matrix:
        ruby-version:
          # We can't test against previous versions of Ruby without extra
          # effort to make mysql2 work. See the link above for more information
          # about the issue we run into:
          #
          #   https://github.com/ruby/setup-ruby/issues/150
          - 2.4.10
          - 2.5.9
          - 2.6.8
          - 2.7.4
          - 3.0.2
        gemfile:
          - gemfiles/Gemfile.rails-4.2.x
          - gemfiles/Gemfile.rails-5.0.x
          - gemfiles/Gemfile.rails-5.1.x
          - gemfiles/Gemfile.rails-5.2.x
          - gemfiles/Gemfile.rails-6.0.x
          - gemfiles/Gemfile.rails-6.1.x
        bundler:
          - 1.17.3
          # Newer Rubies can't use Bundler v1 so we rely on the default v2
          # version instead.
          - null
        exclude:
          # We skip 2.7+ since Rails 4.2 explicitly depends on Bundler 1 which
          # conflicts with the version shipped with those Rubies.
          - gemfile: gemfiles/Gemfile.rails-4.2.x
            ruby-version: 2.7.4
          - gemfile: gemfiles/Gemfile.rails-4.2.x
            ruby-version: 3.0.2

          - gemfile: gemfiles/Gemfile.rails-5.0.x
            ruby-version: 3.0.2
          - gemfile: gemfiles/Gemfile.rails-5.1.x
            ruby-version: 3.0.2
          - gemfile: gemfiles/Gemfile.rails-5.2.x
            ruby-version: 3.0.2

          - gemfile: gemfiles/Gemfile.rails-6.0.x
            ruby-version: 2.4.10
          - gemfile: gemfiles/Gemfile.rails-6.1.x
            ruby-version: 2.4.10

          # Exclude conflicting Ruby-Bundler version pairs.
          - ruby-version: 2.4.10
            bundler: null
          - ruby-version: 2.5.9
            bundler: null
          - ruby-version: 2.6.8
            bundler: null
          - ruby-version: 2.7.4
            bundler: 1.17.3
          - ruby-version: 3.0.2
            bundler: 1.17.3

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true
      - name: Run the test suite against PostgreSQL
        run: bundle exec rake test:postgresql
        env:
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          DATABASE_USERNAME: github
          DATABASE_PASSWORD: github
      - name: Run the test suite against MySQL
        run: bundle exec rake test:mysql2
        env:
          # We can't use localhost because that makes the MySQL client try
          # connecting via a Unix socket instead of TCP.
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 3306
          DATABASE_USERNAME: github
          DATABASE_PASSWORD: github
